# -*- coding: utf-8 -*-
"""Project 1: Climate Change Data Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GK64Iz2jxDfPlmzk-6GY-Yar1Vid-IPA

# Project Scope
Goal: Visualize CO₂ emissions, temperature anomalies, and renewable energy trends for selected countries over time.
# Features:
Interactive line charts for emissions and temperature

Dropdown menu to select countries

Option to compare multiple metrics

Streamlit dashboard layout
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import plotly.express as px

# Load OWID CO₂ dataset
@st.cache_data
def load_data():
    url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"
    df = pd.read_csv(url)
    return df

df = load_data()

df.columns

# Keep only relevant columns
df = df[['country', 'year', 'co2', 'co2_per_capita', 'cumulative_co2', 'co2_growth_prct', 'co2_growth_abs',
         'temperature_change_from_co2', 'temperature_change_from_ghg']]

# Sidebar: country selection
st.sidebar.title("🌍 Climate Change Dashboard")
countries = st.sidebar.multiselect("Select countries", df['country'].unique(),
                                   default=['Kenya', 'India', 'United States'])

# Filter data for selected countries
df = df[df['country'].isin(countries)]
df = df.dropna(subset=['year', 'co2'])

# Main dashboard
st.title("📊 Climate Change Dashboard")
st.markdown("Explore CO₂ emissions, renewable energy trends, and temperature change by country.")

# CO₂ Emissions
st.header("🟠 CO₂ Emissions Over Time")
fig1 = px.line(df, x='year', y='co2', color='country', labels={'co2': 'CO₂ Emissions (million tonnes)'})
st.plotly_chart(fig1, use_container_width=True)

# CO₂ Per Capita
st.header("🧍 CO₂ Emissions Per Capita")
fig2 = px.line(df, x='year', y='co2_per_capita', color='country', labels={'co2_per_capita': 'CO₂ per Capita (tonnes)'})
st.plotly_chart(fig2, use_container_width=True)

# Temperature Change from CO₂
st.header("🌡️ Temperature Change from CO₂")
fig4 = px.line(df, x='year', y='temperature_change_from_co2', color='country',
               labels={'temperature_change_from_co2': 'Temperature Change (°C)'})
st.plotly_chart(fig4, use_container_width=True)

# Temperature Change from All GHGs
st.header("🌡️ Total Temperature Change from GHGs")
fig5 = px.line(df, x='year', y='temperature_change_from_ghg', color='country',
               labels={'temperature_change_from_ghg': 'Temperature Change (°C)'})
st.plotly_chart(fig5, use_container_width=True)

!streamlit run climate_dashboard.py

!pip install -q streamlit pyngrok

dashboard_code = """
import streamlit as st
import pandas as pd
import plotly.express as px

@st.cache_data
def load_data():
    url = "https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv"
    df = pd.read_csv(url)
    return df

df = load_data()

df = df[['country', 'year', 'co2', 'co2_per_capita', 'cumulative_co2', 'co2_growth_prct', 'co2_growth_abs',
         'temperature_change_from_co2', 'temperature_change_from_ghg']]

st.sidebar.title("🌍 Climate Change Dashboard")
countries = st.sidebar.multiselect("Select countries", df['country'].unique(),
                                   default=['Kenya', 'India', 'United States'])

df = df[df['country'].isin(countries)]
df = df.dropna(subset=['year', 'co2'])

st.title("📊 Climate Change Dashboard")
st.markdown("Explore CO₂ emissions, renewable energy trends, and temperature change by country.")

st.header("🟠 CO₂ Emissions Over Time")
fig1 = px.line(df, x='year', y='co2', color='country', labels={'co2': 'CO₂ Emissions (million tonnes)'})
st.plotly_chart(fig1, use_container_width=True)

st.header("🧍 CO₂ Emissions Per Capita")
fig2 = px.line(df, x='year', y='co2_per_capita', color='country', labels={'co2_per_capita': 'CO₂ per Capita (tonnes)'})
st.plotly_chart(fig2, use_container_width=True)

st.header("🌡️ Temperature Change from CO₂")
fig4 = px.line(df, x='year', y='temperature_change_from_co2', color='country',
               labels={'temperature_change_from_co2': 'Temperature Change (°C)'})
st.plotly_chart(fig4, use_container_width=True)

st.header("🌡️ Total Temperature Change from GHGs")
fig5 = px.line(df, x='year', y='temperature_change_from_ghg', color='country',
               labels={'temperature_change_from_ghg': 'Temperature Change (°C)'})
st.plotly_chart(fig5, use_container_width=True)
"""

# Save to a file
with open("climate_dashboard.py", "w") as f:
    f.write(dashboard_code)

# Clean up previous ngrok config
!rm -rf /root/.ngrok2
!rm -rf /root/.config/ngrok

# Reinstall ngrok
!pip uninstall -y pyngrok
!pip install -q pyngrok

#  Add ngrok authtoken
from pyngrok import conf, ngrok

conf.get_default().auth_token = "2s1Pw5f1wJsL15HDSYJ8nZsrC6c_2A3sQwbgC6HVFUZFnFgNq"

# Run the tunnel
ngrok.kill()
public_url = ngrok.connect(8501)
print(f"✅ Your Streamlit app is live at: {public_url}")

# Run the Streamlit app
!streamlit run climate_dashboard.py &>/dev/null &